-- CreateTable
CREATE TABLE "RegisterClose" (
    "id" SERIAL NOT NULL,
    "date" DATE NOT NULL,
    "store_id" INTEGER NOT NULL,
    "groups_count" INTEGER NOT NULL,
    "customer_count" INTEGER NOT NULL,
    "male_count" INTEGER NOT NULL,
    "female_count" INTEGER NOT NULL,
    "unspecified_count" INTEGER NOT NULL,
    "customer_unit_price" DECIMAL(10,2) NOT NULL,
    "total_items_sold" INTEGER NOT NULL,
    "total_sales" DECIMAL(10,2) NOT NULL,
    "consumption_tax" DECIMAL(10,2) NOT NULL,
    "sales_10_percent" DECIMAL(10,2) NOT NULL,
    "tax_10_percent" DECIMAL(10,2) NOT NULL,
    "sales_8_percent" DECIMAL(10,2) NOT NULL,
    "tax_8_percent" DECIMAL(10,2) NOT NULL,
    "sales_tax_free" DECIMAL(10,2) NOT NULL,
    "sales_non_taxable" DECIMAL(10,2) NOT NULL,
    "net_sales" DECIMAL(10,2) NOT NULL,
    "duty_free_items_general" INTEGER NOT NULL,
    "duty_free_items_consumables" INTEGER NOT NULL,
    "duty_free_amount_general" DECIMAL(10,2) NOT NULL,
    "duty_free_amount_consumables" DECIMAL(10,2) NOT NULL,
    "service_charge_count" INTEGER NOT NULL,
    "service_charge" DECIMAL(10,2) NOT NULL,
    "late_night_count" INTEGER NOT NULL,
    "late_night_charge" DECIMAL(10,2) NOT NULL,
    "discount_count" INTEGER NOT NULL,
    "discount_amount" DECIMAL(10,2) NOT NULL,
    "fraction_discount_count" INTEGER NOT NULL,
    "fraction_discount_amount" DECIMAL(10,2) NOT NULL,
    "excluded_count" INTEGER NOT NULL,
    "excluded_amount" DECIMAL(10,2) NOT NULL,
    "cash_count" INTEGER NOT NULL,
    "cash_amount" DECIMAL(10,2) NOT NULL,
    "credit_count" INTEGER NOT NULL,
    "credit_amount" DECIMAL(10,2) NOT NULL,
    "point_count" INTEGER NOT NULL,
    "point_amount" DECIMAL(10,2) NOT NULL,
    "electronic_money_count" INTEGER NOT NULL,
    "electronic_money_amount" DECIMAL(10,2) NOT NULL,
    "gift_card_no_change_count" INTEGER NOT NULL,
    "gift_card_no_change_amount" DECIMAL(10,2) NOT NULL,
    "gift_card_difference" DECIMAL(10,2) NOT NULL,
    "gift_card_with_change_count" INTEGER NOT NULL,
    "gift_card_with_change_amount" DECIMAL(10,2) NOT NULL,
    "gift_card_cash_change" DECIMAL(10,2) NOT NULL,
    "credit_sale_count" INTEGER NOT NULL,
    "credit_sale_amount" DECIMAL(10,2) NOT NULL,
    "cash_on_hand" DECIMAL(10,2) NOT NULL,
    "change_amount" DECIMAL(10,2) NOT NULL,
    "receipt_count" INTEGER NOT NULL,
    "cancel_count" INTEGER NOT NULL,
    "cancel_amount" DECIMAL(10,2) NOT NULL,
    "correction_count" INTEGER NOT NULL,
    "correction_amount" DECIMAL(10,2) NOT NULL,
    "uncollected_count" INTEGER NOT NULL,
    "uncollected_amount" DECIMAL(10,2) NOT NULL,
    "cash_balance" DECIMAL(10,2) NOT NULL,
    "cash_at_open" DECIMAL(10,2) NOT NULL,
    "deposit_count" INTEGER NOT NULL,
    "deposit_amount" DECIMAL(10,2) NOT NULL,
    "withdrawal_count" INTEGER NOT NULL,
    "withdrawal_amount" DECIMAL(10,2) NOT NULL,
    "input_cash" DECIMAL(10,2) NOT NULL,
    "input_credit" DECIMAL(10,2) NOT NULL,
    "input_point" DECIMAL(10,2) NOT NULL,
    "input_electronic_money" DECIMAL(10,2) NOT NULL,
    "input_gift_card_no_change" DECIMAL(10,2) NOT NULL,
    "input_gift_card_with_change" DECIMAL(10,2) NOT NULL,
    "input_credit_sale" DECIMAL(10,2) NOT NULL,
    "total_difference" DECIMAL(10,2) NOT NULL,
    "difference_reason" TEXT,
    "opening_fund" DECIMAL(10,2) NOT NULL,
    "store_deposit" DECIMAL(10,2) NOT NULL,
    "bank_transfer" DECIMAL(10,2) NOT NULL,
    "safe_deposit" DECIMAL(10,2) NOT NULL,
    "security_deposit" DECIMAL(10,2) NOT NULL,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "RegisterClose_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RegisterClose_date_store_id_key" ON "RegisterClose"("date", "store_id");

-- AddForeignKey
ALTER TABLE "RegisterClose" ADD CONSTRAINT "RegisterClose_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
